version: '3.8'

services:
  app:
    build: .
    ports:
      - '3000:3000'  # Исправлено форматирование
    environment:
      PORT: ${PORT}
      DATABASE_URL: postgresql://4pjlst:28052004@host.docker.internal:5433/mydb?schema=public  # Адркс для призмы в коробке
    depends_on:
      - postgres
    restart: on-failure
    networks:
      - app-bridge

  postgres:
    build: ./Dtb/
    ports:
      - '5433:5432'  # Исправлено форматирование
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - app-bridge
    command: >
      postgres -c log_connections=on
               -c log_disconnections=on
               -c log_statement=all

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - ${PGADMIN_PORT}:80  # Исправлено форматирование
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - app-bridge

networks:
  app-bridge:
    driver: bridge

volumes:
  pgdata:
  pgadmin:
